### ISSUE TITLE
关于证书更新是否会对证书中的 X509 中包含的 DNS 进行更改？

### ISSUE THREAD

**Issue by Beherenowhjy** [yuyicai/update-kube-cert#14]
集群版本：1.19
我之前用以下命令更新过集群的apiserver证书，其中包含了高可用域名和各个 master 节点的 主机名 和 ip ，请问使用咱们的脚本更新后，里面的内容是否会有变化？
`kubeadm init phase certs apiserver --config kubeadm.yaml`
![image](https://user-images.githubusercontent.com/59044653/230856882-315eee77-f84f-4082-ad3b-b18dd4574dfd.png)
感谢解答

**Comment by yuyicai** [comment]
脚本会使用旧证书的 `X509v3 Subject Alternative Name`，即和原来保持一致，可以查看脚本 L34 行代码：  
https://github.com/yuyicai/update-kube-cert/blob/master/update-kubeadm-cert.sh#L34

**Comment by Beherenowhjy** [comment]
非常感谢！
