### ISSUE TITLE
How to update ca.crt to delay the expiretime?

### ISSUE THREAD

**Issue by zimu312500** [yuyicai/update-kube-cert#16]

**Comment by yuyicai** [comment]
- 已经安装好的集群轮换 ca 证书是比较麻烦的，你可以参照这里的说明进行轮换：https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/
- ca 证书有效期默认是 10 年，其实时间已经很长了
- 如果你的集群还没开始安装，手动签发有效期更长的 ca 证书放置到 master init 节点对应路径，包含`ca.crt` `front-proxy-ca.crt` `etcd.crt` 以及对应的 key 文件，当执行 kubeadm init 时，它会先检查改路径是否存在有效的 ca 证书，如果存在，那么会优先使用已经存在的ca证书。

**Comment by zimu312500** [comment]
了解，3Q~
