### ISSUE TITLE
1.9版本证书更新问题

### ISSUE THREAD

**Issue by zhongkuiGuo** [yuyicai/update-kube-cert#2]
你好，用脚本跑完之后怎么验证是否生效呢，pki目录下直接openssl看有用吗，高版本的可以通过kubeadm alpha certs check-expiration命令查看，1.9的版本不知道怎么确认，openssl查看是已经改了的。

**Comment by yuyicai** [comment]
脚本更新证书后重启了组件，如果证书不生效集群是起不来的，集群正常说明证书生效
