### ISSUE TITLE
证书更新后有问题

### ISSUE THREAD

**Issue by oldyuan-ops** [yuyicai/update-kube-cert#4]
证书更新后发现确实是更新了十年的，但是拷贝新的admin.conf 无法正常的链接到集群中。

**Comment by yuyicai** [comment]
- 去备份目录看一下旧的 admin.conf，对比一下里面除证书以为的信息看看
- 再试一下旧的 admin.conf 能不能用
- 另外可以贴一下报错信息

**Comment by yuyicai** [comment]
无信息更新，关闭问题
