### ISSUE TITLE
can not find /etc/kubernetes/pki/etcd/ca.crt

### ISSUE THREAD

**Issue by lixiang2017** [yuyicai/update-kube-cert#5]
# log
[root@s1 update-kube-cert]# bash update-kubeadm-cert.sh all
[2021-07-19T16:32:00.768567557+0800]: WARNING: does not backup, /etc/kubernetes.old-20210719 already exists
[2021-07-19T16:32:00.770018187+0800]: ERROR: can not find /etc/kubernetes/pki/etcd/ca.crt
[root@s1 update-kube-cert]#

# version
[root@s1 update-kube-cert]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: x509: certificate has expired or is not yet valid

# tree
```
[root@s1 ~]# tree /etc/kubernetes
/etc/kubernetes
|-- admin.conf
|-- controller-manager.conf
|-- k8sconf.bak
|   |-- admin.conf
|   |-- controller-manager.conf
|   |-- kubelet.conf
|   `-- scheduler.conf
|-- kubelet.conf
|-- manifests
|   |-- kube-apiserver.yaml
|   |-- kube-controller-manager.yaml
|   `-- kube-scheduler.yaml
|-- njwjw.conf
|-- old
|   |-- admin.conf
|   |-- controller-manager.conf
|   |-- kubelet.conf
|   `-- scheduler.conf
|-- pki
|   |-- apiserver.crt
|   |-- apiserver.key
|   |-- apiserver-kubelet-client.crt
|   |-- apiserver-kubelet-client.key
|   |-- ca.crt
|   |-- ca.key
|   |-- front-proxy-ca.crt
|   |-- front-proxy-ca.key
|   |-- front-proxy-client.crt
|   |-- front-proxy-client.key
|   |-- old
|   |   |-- apiserver.crt
|   |   |-- apiserver.crt.old
|   |   |-- apiserver.key
|   |   |-- apiserver.key.old
|   |   |-- apiserver-kubelet-client.crt
|   |   |-- apiserver-kubelet-client.crt.old
|   |   |-- apiserver-kubelet-client.key
|   |   |-- apiserver-kubelet-client.key.old
|   |   |-- front-proxy-client.crt
|   |   |-- front-proxy-client.crt.old
|   |   |-- front-proxy-client.key
|   |   `-- front-proxy-client.key.old
|   |-- sa.key
|   `-- sa.pub
|-- refreshcer.sh
`-- scheduler.conf

5 directories, 41 files
```

**Comment by lixiang2017** [comment]
bash update-kubeadm-cert.sh master

**Comment by KeithTt** [comment]
I check the source code, parameter `all` include two parts: `etcd` and `master`.
