### ISSUE TITLE
更新之后kubelet证书无法更新

### ISSUE THREAD

**Issue by xj90713** [yuyicai/update-kube-cert#6]
你好 我通过kubeadm alpha certs renew all更新完证书之后，kubelet的证书没有更新/var/lib/kubelet/pki。这个需要怎么处理，还是kubelet证书到期之前会自动更新吗？我的版本是v1.19.7

**Comment by yuyicai** [comment]
- 大于 v1.17.x 版本是无需手动处理 master 上的 kubelet 证书，会自动更新
- node 上的 kubelet 无论什么版本也不用手动处理(其实是大于 v1.8.x 版本，现在也没人用这么古老的版本了)，会自动更新

更新证书的源码在这里：https://github.com/kubernetes/kubernetes/blob/v1.19.0/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go#L560-L581
（kubelet 证书会在到期时间的70-90%中随机选择一个时间点来自动更新证书，你现在还没发现自动更新应该是证书还没准备到期）

**Comment by xj90713** [comment]
谢谢了 ，之前模拟时间到期 直接通过设置所有机器到期之后看集群是否可用，发现集群不可用了，那应该是是这个原因，导致kubelet没有轮转更新证书。另外想确认一下我是通过kubeadm安装的集群，kubelet自动更新证书的功能是系统默认的吧，不需要手工设置吧。

**Comment by yuyicai** [comment]
是的，通过 kubeadm 安装的集群，默认都配置了自动更新 kubelet 证书，你需要关心的只有 master 上的证书，node 无需关心
（master上的 etcd 证书、api-apiserver 是不会自动更新的）

如果你还是不放心，可以在 node 节点上检查一下
如何检查是否开启 kubelet 证书自动更新：
- 方法一：查看 kubelet 的 config 文件，里面有一个配置叫 `rotateCertificates: true`
- 方法二：查看 kubelet.conf 文件，如果里面的证书配置如下：
  ```
  client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
  client-key: /var/lib/kubelet/pki/kubelet-client-current.pem
  ```
  并且 /var/lib/kubelet/pki/kubelet-client-current.pem 是一个软连接，链接到一个带日期的命名的证书
  在实际证书轮回过程中，kubelet 会将 /var/lib/kubelet/pki/kubelet-client-current.pem 软连接到新的证书，从而一直保持证书的有效性

**Comment by xj90713** [comment]
好的 多谢了。kubeadm我已经通过源码编译延迟至10年了，已经更新相关master的证书了。
