### ISSUE TITLE
证书更新成功，但已有pod启动有问题

### ISSUE THREAD

**Issue by myf5** [yuyicai/update-kube-cert#9]
你好，我执行脚本后证书更新都成功了。
kubectl get pod -A 也可以看到pod，这些pod都是运行了很久的时间。
当试图重建这些pod后则无法建立了，比如会报如下错误
```
 MountVolume.SetUp failed for volume "flannel-cfg" : failed to sync configmap cache: timed out waiting for the condition
MountVolume.SetUp failed for volume "flannel-token-7qt7z" : failed to sync secret cache: timed out waiting for the condition
```

看上去是cm以及secret在更新证书后，无法被读取了？

**Comment by myf5** [comment]
请教一下这方面的处理经验。感谢

**Comment by yuyicai** [comment]
~你在更新证书之前有动过 /etc/kubernetes 下的东西吗？~  
~默认是服用原来的 CA 和 sa.key 的~  
~你可以先按回退步骤把原来的证书还原回去~

**Comment by yuyicai** [comment]
一开始我还以为是 sa.key 加解密的问题，看来是我判断错了
刚才去搜索了一下你的错误，出现这个报错的场景太多了，233333

**Comment by myf5** [comment]
ca没动过，是的类似错误场景很多。 我上一次一个集群，也是更新完证书后，相关的secret就不能用了。但是那个集群的CNI相关的pod还能正常启动。这次这个集群cni 相关pod也不行了，导致coredns pods也起不了。

新搞了个集群，然后用你的脚本，直接刷成10年了 ，谢啦
再也不要折腾这个证书了。。。

**Comment by yuyicai** [comment]
若没有新的疑问，将关闭该 issue

**Comment by myf5** [comment]
谢谢。
